// ─────────────────────────────────────────────────────────────────────────────
// CUSTOMIZE HERE: names, text, options, timing, and behavior live in one place.
// ─────────────────────────────────────────────────────────────────────────────
export const CONFIG = {
  names: {
    her: 'Nomin-Erdene',
    mine: 'Tumendelger',
  },
  hero: {
    smallHeading: 'An unnecessarily elaborate question',
    headlineFirst: 'I could’ve just sent a text…',
    headlineSecond: 'but you’ve never really inspired the bare minimum.',
    descriptionFirst: 'So here’s me being a little bold:',
    descriptionEmphasis: 'Let me take you on a date.',
    descriptionLast: 'Good conversation, a few laughs, and a website that got slightly out of hand.',
    quoteFirst: 'It might be a questionable idea.',
    quoteSecond: 'It could also be a very good night.',
  },
  reactions: {
    default: '♡',
    yesHover: '♥',
    noHover: '…',
    accepted: '♥',
  },
  decision: {
    title: 'One date. What do you say?',
    subtitle: 'I’ll handle the plan. You bring that dangerously good company.',
    note: 'No grand expectations. I just couldn’t leave a good question unasked.',
  },
  yes: {
    button: 'Okay, take me out',
    bannerLabel: 'A NICE UPDATE',
    breakingNews: 'Looks like we have a date.',
  },
  no: {
    button: 'Tempting, but no',
    dodgeLabels: [
      'Nice try, still no',
      'You’re very determined',
      'This button is fading…',
      'Okay, I’m leaving',
    ],
    dodgeDescriptions: [
      'The button seems to think you meant “not yet.”',
      'It has now confused persistence with charm.',
      'At this point, even the button is quietly rooting for dinner.',
      'The No button has left the building. The Yes button and my unreasonable optimism are still here.',
    ],
    maxDodges: 4,
  },
  loading: [
    'Checking calendars…',
    'Gathering a little courage…',
    'Looks good from here.',
  ],
  planner: {
    eyebrow: 'LET’S MAKE A PLAN',
    heading: 'Here’s the plan. When are you free?',
    intro: 'Dinner at Terrazza, then a walk. Pick a date and add an extra if you want.',
    mainPlan: 'Dinner at Terrazza Restaurant, then a walk',
    recommendation: {
      label: 'TUMENDELGER’S RECOMMENDATION',
      detailsHint: 'Click Dinner at Terrazza Restaurant to see the details and location.',
      dinnerTitle: 'Dinner at Terrazza Restaurant',
      dinnerDetail: 'Mediterranean food and a rooftop view',
      walkTitle: 'A walk after dinner',
      walkDetail: 'Fresh air, no rush, and more time to talk',
      venue: {
        name: 'Terrazza Restaurant',
        address: 'Zaisan Square Center, 8th floor, Ulaanbaatar',
        phone: '+976 7710 2992',
        image: 'terrazza-preview.jpg',
        mapUrl: 'https://www.google.com/maps/search/?api=1&query=Terrazza+Restaurant%2C+%D0%97%D0%B0%D0%B9%D1%81%D0%B0%D0%BD%D0%B3%D0%B8%D0%B9%D0%BD+%D0%B3%D1%83%D0%B4%D0%B0%D0%BC%D0%B6%2C+Zaisan+Square+Center%2C+8th+floor%2C+Ulaanbaatar%2C+Mongolia&query_place_id=ChIJBTvqpm6Tll0RxgRKdfGaY74',
      },
    },
    fields: {
      preferredDate: 'Preferred date',
      preferredTime: 'Preferred time',
      alternativeDate: 'Backup date',
      message: 'A message for me (optional)',
      messagePlaceholder: 'Leave me a note, a question, or anything you want me to know…',
      contact: 'How should I confirm with you? (optional)',
      contactPlaceholder: 'Text, call, Instagram…',
    },
    activities: [
      { id: 'none', emoji: '♡', title: 'Dinner + walk is perfect', detail: 'No extra needed' },
      { id: 'dessert', emoji: '🍰', title: 'Dessert stop', detail: 'Something sweet after the walk' },
      { id: 'coffee', emoji: '☕', title: 'Coffee or bubble tea', detail: 'A relaxed second stop' },
      { id: 'movie', emoji: '🍿', title: 'Movie', detail: 'With good snacks, naturally' },
      { id: 'arcade', emoji: '🕹️', title: 'Arcade or games', detail: 'A little friendly competition' },
      { id: 'surprise', emoji: '✨', title: 'Surprise me', detail: 'Choose one small extra' },
    ],
    submit: 'Save the plan',
    submitting: 'Sending the plan…',
    submissionNote: 'Sent privately when you save the plan.',
    submissionError: 'The plan didn’t send. Please check the connection and try again.',
    submissionSuccess: 'The date plan was sent successfully.',
  },
  formspree: {
    endpoint: 'https://formspree.io/f/mdaqdazd',
    subject: 'New date response',
  },
  confirmation: {
    eyebrow: 'IT’S A DATE',
    heading: 'We have a plan.',
    subheading: 'I’m looking forward to it.',
  },
  footer: 'A little bold. A little cheesy. Completely sincere.',
  storageKey: 'nomin-tumendelger-date-plan-v2',
  loadingStepMs: 900,
} as const
